/* @provenance: BORG-PROVENANCE-STANDARD-2026-03
 * @orchestrator: Magnus Smárason | smarason.is
 * @created: 2026-07-15
 *
 * Classical Music & Opera timeline, Layer 1 (model-generated, canonical).
 * Generated by a 7-agent parallel swarm on 2026-07-15. Layer 2 (Scite
 * scholarly evidence) enrichment is prepped in the classical-music-opera-
 * timeline/research-mission folder. Dates marked "c." are approximate.
 */

export type MusicEntryKind =
  | "opera" | "work" | "composer" | "innovation" | "institution" | "event";

export interface MusicEntry {
  year: number;
  year_label: string;
  title: string;
  composer: string;
  kind: MusicEntryKind;
  description: string;
}

export interface MusicEra {
  id: string;
  name: string;
  start: number;
  end: number;
  blurb: string;
  summary: string;
  key_figures: string[];
  entries: MusicEntry[];
}

export const MUSIC_ERAS: MusicEra[] = [
  {
    "id": "01",
    "name": "Gregorian & Early Plainchant",
    "start": 850,
    "end": 1100,
    "blurb": "Sacred monophonic chant unifies Western worship and notation's birth.",
    "summary": "Latin liturgical chant, later named for Pope Gregory I, becomes the shared musical language of the medieval Church. Monks begin devising ways to notate melodies, laying the foundation for all Western music.",
    "key_figures": [
      "Pope Gregory I",
      "Guido of Arezzo",
      "Hucbald",
      "Notker Balbulus"
    ],
    "entries": [
      {
        "year": 880,
        "year_label": "c.880",
        "title": "Sequences and tropes flourish",
        "composer": "Notker Balbulus",
        "kind": "innovation",
        "description": "Monks at St. Gall expand the liturgy with sequences and tropes, adding new poetic and melodic material to established chant."
      },
      {
        "year": 890,
        "year_label": "c.890",
        "title": "Musica enchiriadis",
        "composer": "Anonymous",
        "kind": "work",
        "description": "An early treatise describing organum, the practice of adding a parallel voice to plainchant, documenting the first steps toward polyphony."
      },
      {
        "year": 1000,
        "year_label": "c.1000",
        "title": "Neumatic notation matures",
        "composer": "Anonymous",
        "kind": "innovation",
        "description": "Scribes refine neumes, symbols placed above text to indicate melodic direction, spreading a memory aid for singers across Europe."
      },
      {
        "year": 1030,
        "year_label": "c.1030",
        "title": "The musical staff",
        "composer": "Guido of Arezzo",
        "kind": "innovation",
        "description": "Guido develops staff lines and a system of solmization, letting singers read unfamiliar melodies at sight for the first time."
      },
      {
        "year": 1050,
        "year_label": "c.1050",
        "title": "Micrologus",
        "composer": "Guido of Arezzo",
        "kind": "work",
        "description": "Guido's influential treatise codifies chant theory, modes, and his teaching methods, becoming a standard text for medieval music education."
      },
      {
        "year": 1090,
        "year_label": "c.1090",
        "title": "Rise of monastic chant centers",
        "composer": "Anonymous",
        "kind": "institution",
        "description": "Abbeys such as Cluny and St. Gall standardize and transmit the chant repertory, preserving liturgical music through careful manuscript copying."
      }
    ]
  },
  {
    "id": "02",
    "name": "Notre-Dame Polyphony / Ars Antiqua",
    "start": 1100,
    "end": 1300,
    "blurb": "Paris cathedral composers build measured polyphony and rhythmic notation.",
    "summary": "At the rising Notre-Dame Cathedral, composers layer multiple independent voices and invent ways to notate rhythm. The motet emerges as a defining new genre of the age.",
    "key_figures": [
      "Léonin",
      "Pérotin",
      "Hildegard of Bingen",
      "Franco of Cologne"
    ],
    "entries": [
      {
        "year": 1150,
        "year_label": "c.1150",
        "title": "Ordo Virtutum",
        "composer": "Hildegard of Bingen",
        "kind": "work",
        "description": "Hildegard composes a visionary morality play with soaring monophonic melodies, one of the earliest known works by a named woman composer."
      },
      {
        "year": 1170,
        "year_label": "c.1170",
        "title": "Magnus Liber Organi",
        "composer": "Léonin",
        "kind": "work",
        "description": "Léonin compiles a great book of two-voice organum for the church year, a cornerstone of the Notre-Dame polyphonic repertory."
      },
      {
        "year": 1200,
        "year_label": "c.1200",
        "title": "Viderunt omnes (four voices)",
        "composer": "Pérotin",
        "kind": "work",
        "description": "Pérotin expands organum to three and four voices, creating grand, sonorous polyphony of unprecedented rhythmic complexity and scale."
      },
      {
        "year": 1250,
        "year_label": "c.1250",
        "title": "Rise of the motet",
        "composer": "Anonymous",
        "kind": "innovation",
        "description": "Composers layer different texts and melodies simultaneously, giving birth to the motet, the most important polyphonic genre of the century."
      },
      {
        "year": 1260,
        "year_label": "c.1260",
        "title": "Rhythmic modes systematized",
        "composer": "Johannes de Garlandia",
        "kind": "innovation",
        "description": "Theorists codify the rhythmic modes, fixed patterns of long and short notes that let performers coordinate measured polyphony."
      },
      {
        "year": 1280,
        "year_label": "c.1280",
        "title": "Ars cantus mensurabilis",
        "composer": "Franco of Cologne",
        "kind": "work",
        "description": "Franco's treatise establishes mensural notation, in which note shapes themselves indicate duration, a decisive advance for rhythmic writing."
      }
    ]
  },
  {
    "id": "03",
    "name": "Ars Nova",
    "start": 1300,
    "end": 1380,
    "blurb": "A new French art refines rhythm, isorhythm, and secular song.",
    "summary": "Fourteenth-century France embraces greater rhythmic freedom, duple meter, and intricate isorhythmic structures. Guillaume de Machaut crowns the era as poet and composer of sacred and secular masterworks.",
    "key_figures": [
      "Philippe de Vitry",
      "Guillaume de Machaut"
    ],
    "entries": [
      {
        "year": 1320,
        "year_label": "c.1320",
        "title": "Ars Nova treatise",
        "composer": "Philippe de Vitry",
        "kind": "work",
        "description": "Vitry's treatise gives the era its name and introduces new notation allowing duple divisions and far more flexible, complex rhythms."
      },
      {
        "year": 1321,
        "year_label": "c.1321",
        "title": "Roman de Fauvel interpolations",
        "composer": "Anonymous",
        "kind": "work",
        "description": "This satirical manuscript preserves early Ars Nova motets, mixing biting political commentary with the new rhythmic and notational techniques."
      },
      {
        "year": 1340,
        "year_label": "c.1340",
        "title": "Isorhythmic motet perfected",
        "composer": "Philippe de Vitry",
        "kind": "innovation",
        "description": "Composers structure motets with repeating rhythmic and melodic patterns, creating vast architectural designs that span entire pieces."
      },
      {
        "year": 1360,
        "year_label": "c.1360",
        "title": "Messe de Nostre Dame",
        "composer": "Guillaume de Machaut",
        "kind": "work",
        "description": "Machaut composes the first complete polyphonic setting of the Mass Ordinary by a single known composer, a landmark of the age."
      },
      {
        "year": 1370,
        "year_label": "c.1370",
        "title": "Secular chanson forms flourish",
        "composer": "Guillaume de Machaut",
        "kind": "innovation",
        "description": "Machaut perfects the formes fixes (ballade, rondeau, virelai), refined courtly songs that dominate French secular music for generations."
      }
    ]
  },
  {
    "id": "04",
    "name": "Italian Trecento",
    "start": 1330,
    "end": 1420,
    "blurb": "Italy's own polyphony blooms in lyrical madrigals and ballate.",
    "summary": "Fourteenth-century Italy develops a distinctive secular polyphony rich in graceful melody and its own notation. The blind Florentine organist Francesco Landini becomes its most celebrated figure.",
    "key_figures": [
      "Jacopo da Bologna",
      "Francesco Landini",
      "Johannes Ciconia"
    ],
    "entries": [
      {
        "year": 1340,
        "year_label": "c.1340",
        "title": "Rise of the Italian madrigal",
        "composer": "Jacopo da Bologna",
        "kind": "innovation",
        "description": "Early Trecento composers cultivate the madrigal, a two-voice secular song setting pastoral poetry with flowing, ornamented upper lines."
      },
      {
        "year": 1350,
        "year_label": "c.1350",
        "title": "Trecento notation of Marchetto",
        "composer": "Marchetto da Padova",
        "kind": "innovation",
        "description": "Italian theorists devise their own system for dividing beats, enabling the refined rhythmic subtlety heard in Trecento secular music."
      },
      {
        "year": 1360,
        "year_label": "c.1360",
        "title": "Rossi Codex",
        "composer": "Anonymous",
        "kind": "work",
        "description": "The earliest major source of Trecento polyphony, this manuscript preserves madrigals and ballate documenting Italy's flowering secular art."
      },
      {
        "year": 1370,
        "year_label": "c.1370",
        "title": "Landini's ballate",
        "composer": "Francesco Landini",
        "kind": "work",
        "description": "The blind Florentine organist Landini composes graceful ballate, lending his name to the Landini cadence, a hallmark of the style."
      },
      {
        "year": 1400,
        "year_label": "c.1400",
        "title": "Squarcialupi Codex compiled",
        "composer": "Anonymous",
        "kind": "work",
        "description": "This lavishly illuminated Florentine manuscript collects the Trecento repertory, portraits and all, becoming its richest surviving anthology."
      },
      {
        "year": 1410,
        "year_label": "c.1410",
        "title": "Ciconia bridges to the north",
        "composer": "Johannes Ciconia",
        "kind": "composer",
        "description": "Working in Italy, this Franco-Flemish master fuses Italian lyricism with French technique, pointing the way toward the early Renaissance."
      }
    ]
  },
  {
    "id": "05",
    "name": "Burgundian & Early Renaissance",
    "start": 1420,
    "end": 1480,
    "blurb": "Sweet English harmony meets Burgundian court song and mass.",
    "summary": "The Burgundian court became Europe's musical center, where composers fused the sweet thirds of English contenance angloise with continental craft. The cyclic cantus-firmus mass and the polished chanson emerged as defining genres.",
    "key_figures": [
      "Guillaume Dufay",
      "Gilles Binchois",
      "John Dunstaple"
    ],
    "entries": [
      {
        "year": 1420,
        "year_label": "c.1420",
        "title": "Contenance angloise",
        "composer": "John Dunstaple",
        "kind": "innovation",
        "description": "English taste for sweet thirds and sixths crossed to the continent, softening harmony and shaping the Burgundian sound."
      },
      {
        "year": 1436,
        "year_label": "1436",
        "title": "Nuper rosarum flores",
        "composer": "Guillaume Dufay",
        "kind": "work",
        "description": "Isorhythmic motet composed for the consecration of Florence's cathedral dome, celebrated for its proportional grandeur."
      },
      {
        "year": 1450,
        "year_label": "c.1450",
        "title": "Cyclic cantus-firmus Mass",
        "composer": "Guillaume Dufay",
        "kind": "innovation",
        "description": "Unifying all Mass movements over a single borrowed tenor melody established the polyphonic Mass as a large-scale structure."
      },
      {
        "year": 1454,
        "year_label": "c.1454",
        "title": "Se la face ay pale Mass",
        "composer": "Guillaume Dufay",
        "kind": "work",
        "description": "A Mass built on Dufay's own secular chanson tune, a landmark of the cantus-firmus technique."
      },
      {
        "year": 1460,
        "year_label": "c.1460",
        "title": "Burgundian chanson flowering",
        "composer": "Gilles Binchois",
        "kind": "work",
        "description": "Refined three-voice courtly love songs set the elegant standard for secular polyphony at the Burgundian court."
      },
      {
        "year": 1477,
        "year_label": "1477",
        "title": "Fall of the Burgundian court",
        "composer": "Antoine Busnois",
        "kind": "event",
        "description": "The death of Charles the Bold ended the Burgundian court's golden age, dispersing its musical culture across Europe."
      }
    ]
  },
  {
    "id": "06",
    "name": "Franco-Flemish Polyphony",
    "start": 1480,
    "end": 1560,
    "blurb": "Josquin's generation perfects imitative counterpoint and music printing.",
    "summary": "Franco-Flemish masters spread pervasive imitation across Europe, making every voice equal in a seamless polyphonic weave. Josquin des Prez became the era's towering figure just as printing began to circulate music widely.",
    "key_figures": [
      "Josquin des Prez",
      "Johannes Ockeghem",
      "Jacob Obrecht",
      "Nicolas Gombert"
    ],
    "entries": [
      {
        "year": 1480,
        "year_label": "c.1480",
        "title": "Missa prolationum",
        "composer": "Johannes Ockeghem",
        "kind": "work",
        "description": "A tour de force of mensuration canon, showing the intellectual heights of late-fifteenth-century Flemish counterpoint."
      },
      {
        "year": 1500,
        "year_label": "c.1500",
        "title": "Ave Maria virgo serena",
        "composer": "Josquin des Prez",
        "kind": "work",
        "description": "A model of clear imitative polyphony, its paired-voice entries became a benchmark of Renaissance sacred style."
      },
      {
        "year": 1501,
        "year_label": "1501",
        "title": "Harmonice Musices Odhecaton",
        "composer": "Ottaviano Petrucci",
        "kind": "innovation",
        "description": "The first substantial book of polyphonic music printed from movable type, launching commercial music publishing in Venice."
      },
      {
        "year": 1502,
        "year_label": "1502",
        "title": "Missa Pange lingua",
        "composer": "Josquin des Prez",
        "kind": "work",
        "description": "A paraphrase Mass dissolving a chant hymn into all voices, a summit of Josquin's mature imitative art."
      },
      {
        "year": 1547,
        "year_label": "1547",
        "title": "Dodecachordon",
        "composer": "Heinrich Glarean",
        "kind": "innovation",
        "description": "Theoretical treatise proposing twelve modes and praising Josquin, codifying the era's musical thought."
      },
      {
        "year": 1550,
        "year_label": "c.1550",
        "title": "Pervasive imitation matured",
        "composer": "Nicolas Gombert",
        "kind": "innovation",
        "description": "Dense, seamless textures with continuous overlapping imitation defined the high Franco-Flemish style before Palestrina."
      }
    ]
  },
  {
    "id": "07",
    "name": "Counter-Reformation Sacred",
    "start": 1545,
    "end": 1610,
    "blurb": "Rome purifies sacred polyphony; clarity of the word restored.",
    "summary": "Responding to the Council of Trent's call for intelligible sacred music, Palestrina and his contemporaries refined a serene, transparent polyphony. Rome became the model of Catholic liturgical style even as Venice pursued grand cori spezzati splendor.",
    "key_figures": [
      "Giovanni Pierluigi da Palestrina",
      "Tomás Luis de Victoria",
      "Orlando di Lasso",
      "Giovanni Gabrieli"
    ],
    "entries": [
      {
        "year": 1545,
        "year_label": "1545",
        "title": "Council of Trent opens",
        "composer": "Roman Catholic Church",
        "kind": "event",
        "description": "The reforming council eventually urged that sacred polyphony keep sacred texts intelligible, shaping church music for generations."
      },
      {
        "year": 1567,
        "year_label": "1567",
        "title": "Missa Papae Marcelli",
        "composer": "Giovanni Pierluigi da Palestrina",
        "kind": "work",
        "description": "Legendary for its clarity of text within rich polyphony, it became the emblem of reformed Catholic church music."
      },
      {
        "year": 1572,
        "year_label": "1572",
        "title": "Motecta collection",
        "composer": "Orlando di Lasso",
        "kind": "work",
        "description": "Lasso's cosmopolitan motets, blending expressive intensity with craft, spread the Franco-Flemish master's fame across Europe."
      },
      {
        "year": 1585,
        "year_label": "1585",
        "title": "Officium Hebdomadae Sanctae",
        "composer": "Tomás Luis de Victoria",
        "kind": "work",
        "description": "Victoria's intense Holy Week settings brought Spanish mystical fervor to the Counter-Reformation sacred repertory."
      },
      {
        "year": 1597,
        "year_label": "1597",
        "title": "Sacrae symphoniae",
        "composer": "Giovanni Gabrieli",
        "kind": "work",
        "description": "Grand polychoral works for St Mark's, Venice, exploiting spatial cori spezzati and early instrumental specification."
      },
      {
        "year": 1605,
        "year_label": "1605",
        "title": "Cantiones Sacrae",
        "composer": "William Byrd",
        "kind": "work",
        "description": "Byrd's Latin motets voiced devout Catholic sentiment in Protestant England, masterworks of expressive sacred polyphony."
      }
    ]
  },
  {
    "id": "08",
    "name": "The Madrigal & Late Renaissance",
    "start": 1530,
    "end": 1620,
    "blurb": "The Italian madrigal marries poetry to daring expressive harmony.",
    "summary": "The madrigal made secular vocal music a laboratory for word-painting and bold chromatic emotion. From Willaert's early refinement to Gesualdo's shocking harmony and Monteverdi's dramatic seconda pratica, expression pushed toward the coming Baroque.",
    "key_figures": [
      "Cipriano de Rore",
      "Luca Marenzio",
      "Carlo Gesualdo",
      "Claudio Monteverdi"
    ],
    "entries": [
      {
        "year": 1530,
        "year_label": "1530",
        "title": "First book of madrigals printed",
        "composer": "Philippe Verdelot",
        "kind": "innovation",
        "description": "Early published madrigals launched Italy's new expressive secular genre, wedding fine poetry to responsive polyphony."
      },
      {
        "year": 1542,
        "year_label": "1542",
        "title": "Madrigals of Cipriano de Rore",
        "composer": "Cipriano de Rore",
        "kind": "work",
        "description": "Rore intensified word-painting and chromatic expression, making the madrigal a serious vehicle for poetic emotion."
      },
      {
        "year": 1587,
        "year_label": "1587",
        "title": "First Book of Madrigals",
        "composer": "Claudio Monteverdi",
        "kind": "work",
        "description": "Monteverdi's debut madrigal book began a career that would carry the genre from polyphony toward dramatic monody."
      },
      {
        "year": 1590,
        "year_label": "1590",
        "title": "Madrigals of Luca Marenzio",
        "composer": "Luca Marenzio",
        "kind": "work",
        "description": "Marenzio's vivid, virtuosic word-painting made him the most admired madrigalist of the late sixteenth century."
      },
      {
        "year": 1605,
        "year_label": "1605",
        "title": "Fifth Book of Madrigals",
        "composer": "Claudio Monteverdi",
        "kind": "work",
        "description": "Its preface defended the seconda pratica, where the words command the harmony, heralding the expressive Baroque."
      },
      {
        "year": 1611,
        "year_label": "1611",
        "title": "Fifth and Sixth Books of Madrigals",
        "composer": "Carlo Gesualdo",
        "kind": "work",
        "description": "Gesualdo's extreme chromaticism and dissonance pushed tonal expression to a startling, harmonically radical extreme."
      }
    ]
  },
  {
    "id": "09",
    "name": "Monody & the Florentine Camerata",
    "start": 1580,
    "end": 1610,
    "blurb": "Florentine intellectuals revive solo song to reform music.",
    "summary": "A circle of Florentine humanists sought to recover the expressive power of ancient Greek drama by championing solo singing over dense polyphony. Their theories of monody and recitative laid the groundwork for opera.",
    "key_figures": [
      "Giovanni de' Bardi",
      "Vincenzo Galilei",
      "Giulio Caccini",
      "Jacopo Peri"
    ],
    "entries": [
      {
        "year": 1573,
        "year_label": "c.1573",
        "title": "Florentine Camerata forms",
        "composer": "Giovanni de' Bardi",
        "kind": "institution",
        "description": "A circle of Florentine humanists, poets, and musicians gathers to debate reviving ancient Greek music and drama."
      },
      {
        "year": 1581,
        "year_label": "1581",
        "title": "Dialogo della musica antica et della moderna",
        "composer": "Vincenzo Galilei",
        "kind": "innovation",
        "description": "Galilei's treatise attacks contrapuntal polyphony and argues for solo song that follows the natural inflections of speech."
      },
      {
        "year": 1589,
        "year_label": "1589",
        "title": "La Pellegrina intermedi",
        "composer": "Various",
        "kind": "event",
        "description": "Lavish musical interludes for a Medici wedding gather leading composers and foreshadow the union of music and staged spectacle."
      },
      {
        "year": 1600,
        "year_label": "1600",
        "title": "Il rapimento di Cefalo",
        "composer": "Giulio Caccini",
        "kind": "work",
        "description": "Caccini's staged work for a Medici wedding showcases the new monodic style before Florentine nobility."
      },
      {
        "year": 1602,
        "year_label": "1602",
        "title": "Le nuove musiche",
        "composer": "Giulio Caccini",
        "kind": "work",
        "description": "A landmark collection of solo songs codifying the new monodic style, with a preface explaining expressive ornamentation and recitative."
      }
    ]
  },
  {
    "id": "10",
    "name": "The Birth of Opera",
    "start": 1598,
    "end": 1650,
    "blurb": "Sung drama emerges and matures into a public art.",
    "summary": "Building on Camerata theory, composers created fully sung dramas, beginning in Florentine courts and culminating in Monteverdi's masterworks. Opera then spread to Rome and Venice, where the first public opera house opened.",
    "key_figures": [
      "Jacopo Peri",
      "Claudio Monteverdi",
      "Francesco Cavalli"
    ],
    "entries": [
      {
        "year": 1598,
        "year_label": "c.1598",
        "title": "Dafne",
        "composer": "Jacopo Peri",
        "kind": "opera",
        "description": "Generally regarded as the first opera, this Florentine work set an entire drama to music, though its score survives only in fragments."
      },
      {
        "year": 1600,
        "year_label": "1600",
        "title": "Euridice",
        "composer": "Jacopo Peri",
        "kind": "opera",
        "description": "The earliest surviving opera, composed for a Medici wedding and pioneering continuous recitative to carry the dramatic action."
      },
      {
        "year": 1607,
        "year_label": "1607",
        "title": "L'Orfeo",
        "composer": "Claudio Monteverdi",
        "kind": "opera",
        "description": "The first operatic masterpiece, uniting rich orchestration, expressive recitative, and formal design into a fully realized dramatic work."
      },
      {
        "year": 1637,
        "year_label": "1637",
        "title": "Teatro San Cassiano opens",
        "composer": "Various",
        "kind": "institution",
        "description": "The first public opera house opens in Venice, transforming opera from courtly entertainment into a paying public spectacle."
      },
      {
        "year": 1642,
        "year_label": "1642",
        "title": "L'incoronazione di Poppea",
        "composer": "Claudio Monteverdi",
        "kind": "opera",
        "description": "One of the first operas on a historical subject, notable for its psychological depth and morally ambiguous human characters."
      },
      {
        "year": 1649,
        "year_label": "1649",
        "title": "Giasone",
        "composer": "Francesco Cavalli",
        "kind": "opera",
        "description": "Among the most popular operas of the century, cementing Venetian public opera with tuneful arias and clear comic and serious scenes."
      }
    ]
  },
  {
    "id": "11",
    "name": "Early Baroque: Oratorio & Cantata",
    "start": 1620,
    "end": 1680,
    "blurb": "New sacred and chamber vocal genres flourish across Italy.",
    "summary": "Alongside opera, composers developed the oratorio and the chamber cantata, extending dramatic vocal writing into sacred and intimate settings. French and English courts began forging their own national styles.",
    "key_figures": [
      "Giacomo Carissimi",
      "Heinrich Schütz",
      "Jean-Baptiste Lully",
      "Barbara Strozzi"
    ],
    "entries": [
      {
        "year": 1637,
        "year_label": "c.1637",
        "title": "Barbara Strozzi's cantatas",
        "composer": "Barbara Strozzi",
        "kind": "innovation",
        "description": "A leading composer and singer publishes acclaimed volumes of secular chamber cantatas, an unusual feat for a woman of the era."
      },
      {
        "year": 1650,
        "year_label": "c.1650",
        "title": "Jephte",
        "composer": "Giacomo Carissimi",
        "kind": "work",
        "description": "A celebrated Latin oratorio whose dramatic recitatives and moving final chorus set a model for the genre across Europe."
      },
      {
        "year": 1664,
        "year_label": "1664",
        "title": "Lully begins court operas",
        "composer": "Jean-Baptiste Lully",
        "kind": "composer",
        "description": "Lully rises as director of French court music, forging a national style with the tragedie en musique and the French overture."
      },
      {
        "year": 1672,
        "year_label": "1672",
        "title": "Academie Royale de Musique monopoly",
        "composer": "Jean-Baptiste Lully",
        "kind": "institution",
        "description": "Lully secures royal control over opera in France, dominating Parisian musical life and shaping French operatic taste for decades."
      },
      {
        "year": 1678,
        "year_label": "1678",
        "title": "Theater am Gansemarkt opens",
        "composer": "Various",
        "kind": "institution",
        "description": "Hamburg opens the first major public opera house in the German-speaking world, nurturing a native German operatic tradition."
      }
    ]
  },
  {
    "id": "12",
    "name": "Opera Seria & the Late Baroque",
    "start": 1680,
    "end": 1750,
    "blurb": "Virtuosic Italian opera and instrumental mastery reach their peak.",
    "summary": "Opera seria standardized serious Italian opera around da capo arias and star singers, while composers like Corelli, Vivaldi, Bach, and Handel brought Baroque instrumental and choral music to its height. The era closes with Bach's death in 1750.",
    "key_figures": [
      "Arcangelo Corelli",
      "Antonio Vivaldi",
      "George Frideric Handel",
      "Johann Sebastian Bach",
      "Alessandro Scarlatti"
    ],
    "entries": [
      {
        "year": 1689,
        "year_label": "1689",
        "title": "Dido and Aeneas",
        "composer": "Henry Purcell",
        "kind": "opera",
        "description": "England's first great opera, compact and deeply expressive, culminating in Dido's Lament over a descending ground bass."
      },
      {
        "year": 1700,
        "year_label": "c.1700",
        "title": "Corelli's Op. 5 sonatas",
        "composer": "Arcangelo Corelli",
        "kind": "work",
        "description": "Corelli's violin sonatas set the standard for Baroque instrumental style and violin technique across all of Europe."
      },
      {
        "year": 1711,
        "year_label": "1711",
        "title": "Rinaldo",
        "composer": "George Frideric Handel",
        "kind": "opera",
        "description": "Handel's first Italian opera for London, a triumph of virtuosic da capo arias that established him on the English stage."
      },
      {
        "year": 1725,
        "year_label": "1725",
        "title": "The Four Seasons",
        "composer": "Antonio Vivaldi",
        "kind": "work",
        "description": "A set of programmatic violin concertos that became the most famous example of Baroque concerto writing and musical depiction."
      },
      {
        "year": 1727,
        "year_label": "1727",
        "title": "St Matthew Passion",
        "composer": "Johann Sebastian Bach",
        "kind": "work",
        "description": "Bach's monumental setting of the Passion narrative crowns the Lutheran sacred tradition with double choir and profound expressivity."
      },
      {
        "year": 1741,
        "year_label": "1741",
        "title": "Messiah",
        "composer": "George Frideric Handel",
        "kind": "work",
        "description": "Handel's English oratorio, composed in weeks, became the most beloved choral work in the repertoire and eclipsed his opera career."
      },
      {
        "year": 1750,
        "year_label": "1750",
        "title": "Death of J. S. Bach",
        "composer": "Johann Sebastian Bach",
        "kind": "event",
        "description": "Bach's death is traditionally taken to mark the end of the Baroque era in music history."
      }
    ]
  },
  {
    "id": "13",
    "name": "The Galant & Early Classical Style",
    "start": 1730,
    "end": 1770,
    "blurb": "Light, elegant textures displace Baroque counterpoint across Europe.",
    "summary": "Composers embraced the galant style's grace, clear melody, and simple harmony, moving away from Baroque complexity. New forms like the symphony and sonata began taking shape at Mannheim and beyond.",
    "key_figures": [
      "Carl Philipp Emanuel Bach",
      "Domenico Scarlatti",
      "Johann Stamitz",
      "Giovanni Battista Pergolesi"
    ],
    "entries": [
      {
        "year": 1733,
        "year_label": "1733",
        "title": "La serva padrona",
        "composer": "Giovanni Battista Pergolesi",
        "kind": "opera",
        "description": "Comic intermezzo that became a model for opera buffa and later sparked the Querelle des Bouffons in Paris."
      },
      {
        "year": 1738,
        "year_label": "c.1738",
        "title": "Scarlatti's keyboard sonatas mature",
        "composer": "Domenico Scarlatti",
        "kind": "work",
        "description": "Single-movement sonatas with bold figuration and Iberian color expanded keyboard technique and binary form."
      },
      {
        "year": 1742,
        "year_label": "1742",
        "title": "Wurttemberg Sonatas",
        "composer": "Carl Philipp Emanuel Bach",
        "kind": "work",
        "description": "Empfindsamer style keyboard works prized expressive, sudden shifts of feeling that pointed toward Classical sensibility."
      },
      {
        "year": 1745,
        "year_label": "c.1745",
        "title": "The Mannheim orchestra and its crescendo",
        "composer": "Johann Stamitz",
        "kind": "innovation",
        "description": "Stamitz drilled a virtuoso orchestra famed for dynamic crescendos and unified bowing, advancing early symphonic style."
      },
      {
        "year": 1752,
        "year_label": "1752",
        "title": "Essay on the True Art of Playing Keyboard Instruments",
        "composer": "Carl Philipp Emanuel Bach",
        "kind": "work",
        "description": "Influential treatise codifying ornamentation, fingering, and expression that guided a generation including Haydn and Mozart."
      },
      {
        "year": 1759,
        "year_label": "1759",
        "title": "Death of George Frideric Handel",
        "composer": "George Frideric Handel",
        "kind": "event",
        "description": "Handel's death closed the Baroque era in England as galant and early Classical idioms took hold."
      }
    ]
  },
  {
    "id": "14",
    "name": "Gluck's Reform & Classical Opera",
    "start": 1762,
    "end": 1800,
    "blurb": "Opera reformed to serve drama with noble simplicity.",
    "summary": "Gluck's reforms subordinated virtuoso display to dramatic truth, reshaping serious opera across Vienna and Paris. His ideals influenced Mozart and the broader Classical operatic stage.",
    "key_figures": [
      "Christoph Willibald Gluck",
      "Wolfgang Amadeus Mozart",
      "Ranieri de' Calzabigi"
    ],
    "entries": [
      {
        "year": 1762,
        "year_label": "1762",
        "title": "Orfeo ed Euridice",
        "composer": "Christoph Willibald Gluck",
        "kind": "opera",
        "description": "The founding reform opera, with Calzabigi's libretto, prized dramatic continuity and simplicity over ornamental display."
      },
      {
        "year": 1767,
        "year_label": "1767",
        "title": "Alceste",
        "composer": "Christoph Willibald Gluck",
        "kind": "opera",
        "description": "Its published preface laid out Gluck's reform manifesto, calling music the servant of poetry and drama."
      },
      {
        "year": 1774,
        "year_label": "1774",
        "title": "Iphigenie en Aulide",
        "composer": "Christoph Willibald Gluck",
        "kind": "opera",
        "description": "Gluck brought his reform ideals to Paris, adapting French tragedie lyrique to a leaner dramatic style."
      },
      {
        "year": 1779,
        "year_label": "1779",
        "title": "Iphigenie en Tauride",
        "composer": "Christoph Willibald Gluck",
        "kind": "opera",
        "description": "Regarded as Gluck's masterpiece, it fused orchestral drama and psychological depth on the Paris stage."
      },
      {
        "year": 1781,
        "year_label": "1781",
        "title": "Idomeneo",
        "composer": "Wolfgang Amadeus Mozart",
        "kind": "opera",
        "description": "Mozart's grand opera seria absorbed Gluckian reform, uniting chorus, orchestra, and drama with new power."
      },
      {
        "year": 1786,
        "year_label": "1786",
        "title": "The Marriage of Figaro",
        "composer": "Wolfgang Amadeus Mozart",
        "kind": "opera",
        "description": "With librettist Da Ponte, Mozart raised opera buffa to a summit of ensemble writing and human comedy."
      },
      {
        "year": 1791,
        "year_label": "1791",
        "title": "The Magic Flute",
        "composer": "Wolfgang Amadeus Mozart",
        "kind": "opera",
        "description": "A German Singspiel blending folk comedy, Masonic solemnity, and sublime music into a beloved fairy-tale opera."
      }
    ]
  },
  {
    "id": "15",
    "name": "High Classicism: Haydn & Mozart",
    "start": 1770,
    "end": 1800,
    "blurb": "Sonata form, symphony, and quartet reach classical perfection.",
    "summary": "Haydn and Mozart brought the symphony, string quartet, and sonata form to full maturity in Vienna. Their balance of form and expression defined the Classical style at its height.",
    "key_figures": [
      "Joseph Haydn",
      "Wolfgang Amadeus Mozart"
    ],
    "entries": [
      {
        "year": 1772,
        "year_label": "1772",
        "title": "Symphony No. 45 'Farewell'",
        "composer": "Joseph Haydn",
        "kind": "work",
        "description": "A Sturm und Drang symphony whose fading finale showed Haydn's wit and growing expressive range at Esterhaza."
      },
      {
        "year": 1781,
        "year_label": "1781",
        "title": "Op. 33 String Quartets",
        "composer": "Joseph Haydn",
        "kind": "work",
        "description": "Written 'in a new and special way,' these quartets crystallized the mature Classical dialogue among four voices."
      },
      {
        "year": 1785,
        "year_label": "1785",
        "title": "'Haydn' Quartets dedicated",
        "composer": "Wolfgang Amadeus Mozart",
        "kind": "work",
        "description": "Mozart dedicated six string quartets to Haydn, a mutual tribute at the peak of Classical chamber writing."
      },
      {
        "year": 1787,
        "year_label": "1787",
        "title": "Don Giovanni",
        "composer": "Wolfgang Amadeus Mozart",
        "kind": "opera",
        "description": "A dramma giocoso mixing comedy and the demonic, culminating in the Don's descent, hailed as a supreme opera."
      },
      {
        "year": 1788,
        "year_label": "1788",
        "title": "Symphonies Nos. 40 and 41 'Jupiter'",
        "composer": "Wolfgang Amadeus Mozart",
        "kind": "work",
        "description": "His final symphonies, composed in weeks, crowned the Classical symphony with lyric intensity and contrapuntal grandeur."
      },
      {
        "year": 1791,
        "year_label": "1791",
        "title": "'London' Symphonies",
        "composer": "Joseph Haydn",
        "kind": "work",
        "description": "Haydn's triumphant London visits produced twelve symphonies that set the standard for the mature Classical orchestra."
      },
      {
        "year": 1798,
        "year_label": "1798",
        "title": "The Creation",
        "composer": "Joseph Haydn",
        "kind": "work",
        "description": "A grand oratorio depicting the world's making, uniting Handelian chorus with Classical orchestral color and word-painting."
      }
    ]
  },
  {
    "id": "16",
    "name": "Beethoven & Early Romanticism",
    "start": 1795,
    "end": 1830,
    "blurb": "Beethoven expands form as Romantic expression emerges.",
    "summary": "Beethoven transformed the symphony, sonata, and quartet, expanding scale and emotional depth toward Romanticism. Schubert's lieder and lyric gifts opened new expressive territory as the Classical era closed.",
    "key_figures": [
      "Ludwig van Beethoven",
      "Franz Schubert"
    ],
    "entries": [
      {
        "year": 1804,
        "year_label": "1804",
        "title": "Symphony No. 3 'Eroica'",
        "composer": "Ludwig van Beethoven",
        "kind": "work",
        "description": "Vast in scale and heroic in tone, the Eroica broke symphonic bounds and inaugurated Beethoven's middle period."
      },
      {
        "year": 1805,
        "year_label": "1805",
        "title": "Fidelio",
        "composer": "Ludwig van Beethoven",
        "kind": "opera",
        "description": "Beethoven's only opera, a rescue drama exalting freedom and marital devotion, revised across three versions."
      },
      {
        "year": 1808,
        "year_label": "1808",
        "title": "Symphony No. 5",
        "composer": "Ludwig van Beethoven",
        "kind": "work",
        "description": "Its four-note motto drives a journey from struggle to triumph, becoming the most famous symphony ever written."
      },
      {
        "year": 1814,
        "year_label": "1814",
        "title": "'Gretchen am Spinnrade'",
        "composer": "Franz Schubert",
        "kind": "work",
        "description": "At seventeen Schubert fused voice and piano into a new dramatic lied, founding the Romantic art song."
      },
      {
        "year": 1824,
        "year_label": "1824",
        "title": "Symphony No. 9 'Choral'",
        "composer": "Ludwig van Beethoven",
        "kind": "work",
        "description": "The finale's 'Ode to Joy' added voices to the symphony, a visionary anthem to universal brotherhood."
      },
      {
        "year": 1827,
        "year_label": "1827",
        "title": "Death of Beethoven",
        "composer": "Ludwig van Beethoven",
        "kind": "event",
        "description": "Beethoven's Vienna funeral drew tens of thousands, marking the passing of the towering figure of the age."
      },
      {
        "year": 1828,
        "year_label": "1828",
        "title": "Winterreise and death of Schubert",
        "composer": "Franz Schubert",
        "kind": "work",
        "description": "His bleak song cycle capped a brief life, leaving a vast lieder legacy that shaped Romantic song."
      }
    ]
  },
  {
    "id": "17",
    "name": "Bel Canto Opera",
    "start": 1810,
    "end": 1850,
    "blurb": "Italian opera prizes beautiful, agile, expressive vocal line.",
    "summary": "Rossini, Bellini, and Donizetti perfected the bel canto style, emphasizing lyrical melody, virtuosic ornamentation, and dramatic vocal expression. The era produced enduring comic and tragic operas that still anchor the repertoire.",
    "key_figures": [
      "Gioachino Rossini",
      "Vincenzo Bellini",
      "Gaetano Donizetti"
    ],
    "entries": [
      {
        "year": 1816,
        "year_label": "1816",
        "title": "The Barber of Seville",
        "composer": "Gioachino Rossini",
        "kind": "opera",
        "description": "Rossini's sparkling comic masterpiece, the definitive opera buffa, celebrated for its wit and virtuosic vocal writing."
      },
      {
        "year": 1831,
        "year_label": "1831",
        "title": "La sonnambula",
        "composer": "Vincenzo Bellini",
        "kind": "opera",
        "description": "Pastoral bel canto tragedy showcasing Bellini's flowing lyricism and demanding coloratura for soprano."
      },
      {
        "year": 1831,
        "year_label": "1831",
        "title": "Norma",
        "composer": "Vincenzo Bellini",
        "kind": "opera",
        "description": "Bellini's tragic bel canto summit, its aria 'Casta diva' epitomizing long-breathed, pure melodic line."
      },
      {
        "year": 1835,
        "year_label": "1835",
        "title": "Lucia di Lammermoor",
        "composer": "Gaetano Donizetti",
        "kind": "opera",
        "description": "Donizetti's tragic masterpiece, famed for its 'mad scene' displaying dazzling coloratura and dramatic intensity."
      },
      {
        "year": 1840,
        "year_label": "1840",
        "title": "La fille du regiment",
        "composer": "Gaetano Donizetti",
        "kind": "opera",
        "description": "Comic opera celebrated for its tenor aria with nine high Cs, a bel canto virtuosity landmark."
      },
      {
        "year": 1843,
        "year_label": "1843",
        "title": "Don Pasquale",
        "composer": "Gaetano Donizetti",
        "kind": "opera",
        "description": "One of the last great opera buffa works, blending comic vitality with refined melodic charm."
      }
    ]
  },
  {
    "id": "18",
    "name": "Romantic Orchestra & Lieder",
    "start": 1830,
    "end": 1870,
    "blurb": "Expanded orchestra, programmatic color, and intimate German song.",
    "summary": "Composers enlarged the orchestra's expressive and coloristic range while pioneering program music and the symphonic poem. Alongside these public forms, the German Lied and Romantic piano miniature flourished as intimate personal expression.",
    "key_figures": [
      "Hector Berlioz",
      "Felix Mendelssohn",
      "Robert Schumann",
      "Frederic Chopin",
      "Franz Liszt",
      "Johannes Brahms"
    ],
    "entries": [
      {
        "year": 1830,
        "year_label": "1830",
        "title": "Symphonie fantastique",
        "composer": "Hector Berlioz",
        "kind": "work",
        "description": "Berlioz's autobiographical program symphony, revolutionary in orchestration and its recurring 'idee fixe' theme."
      },
      {
        "year": 1839,
        "year_label": "1839",
        "title": "Preludes, Op. 28",
        "composer": "Frederic Chopin",
        "kind": "work",
        "description": "Chopin's cycle of piano miniatures, distilling the Romantic character piece to concentrated poetic essence."
      },
      {
        "year": 1840,
        "year_label": "1840",
        "title": "Dichterliebe",
        "composer": "Robert Schumann",
        "kind": "work",
        "description": "Schumann's song cycle on Heine, a summit of the German Lied uniting voice and piano poetry."
      },
      {
        "year": 1846,
        "year_label": "1846",
        "title": "Elijah",
        "composer": "Felix Mendelssohn",
        "kind": "work",
        "description": "Mendelssohn's oratorio premiered in Birmingham, reviving the grand Handelian tradition with Romantic warmth."
      },
      {
        "year": 1854,
        "year_label": "1854",
        "title": "Les preludes",
        "composer": "Franz Liszt",
        "kind": "innovation",
        "description": "Liszt's third symphonic poem, defining the new single-movement orchestral genre built on thematic transformation."
      },
      {
        "year": 1868,
        "year_label": "1868",
        "title": "A German Requiem",
        "composer": "Johannes Brahms",
        "kind": "work",
        "description": "Brahms's large-scale choral-orchestral meditation on consolation, drawn from German scripture rather than the Latin Mass."
      }
    ]
  },
  {
    "id": "19",
    "name": "French Grand Opera",
    "start": 1831,
    "end": 1870,
    "blurb": "Lavish Parisian spectacle with history, ballet, and chorus.",
    "summary": "Paris cultivated grand opera on an epic scale, combining historical drama, spectacular staging, large choruses, and obligatory ballet. Meyerbeer and Auber dominated the Opera, shaping a monumental style that influenced composers across Europe.",
    "key_figures": [
      "Giacomo Meyerbeer",
      "Daniel Auber",
      "Fromental Halevy"
    ],
    "entries": [
      {
        "year": 1828,
        "year_label": "1828",
        "title": "La muette de Portici",
        "composer": "Daniel Auber",
        "kind": "opera",
        "description": "Often cited as the first French grand opera, its revolutionary subject even sparked political unrest at performance."
      },
      {
        "year": 1831,
        "year_label": "1831",
        "title": "Robert le diable",
        "composer": "Giacomo Meyerbeer",
        "kind": "opera",
        "description": "Meyerbeer's sensational Paris triumph, its supernatural spectacle establishing the grand opera formula's dominance."
      },
      {
        "year": 1835,
        "year_label": "1835",
        "title": "La Juive",
        "composer": "Fromental Halevy",
        "kind": "opera",
        "description": "Halevy's grand opera of religious persecution, monumental in scale and long a staple of the Paris repertoire."
      },
      {
        "year": 1836,
        "year_label": "1836",
        "title": "Les Huguenots",
        "composer": "Giacomo Meyerbeer",
        "kind": "opera",
        "description": "Meyerbeer's masterpiece dramatizing the St. Bartholomew's Day massacre, a benchmark of grand operatic spectacle."
      },
      {
        "year": 1849,
        "year_label": "1849",
        "title": "Le prophete",
        "composer": "Giacomo Meyerbeer",
        "kind": "opera",
        "description": "Meyerbeer grand opera famed for its skating ballet and pioneering use of electric arc-light stage effects."
      },
      {
        "year": 1865,
        "year_label": "1865",
        "title": "L'Africaine",
        "composer": "Giacomo Meyerbeer",
        "kind": "opera",
        "description": "Meyerbeer's posthumously premiered final grand opera, a lavish exotic epic capping the Parisian tradition."
      }
    ]
  },
  {
    "id": "20",
    "name": "Verdi & Italian Romantic Opera",
    "start": 1842,
    "end": 1893,
    "blurb": "Verdi brings dramatic power and human depth to opera.",
    "summary": "Giuseppe Verdi dominated Italian opera for half a century, deepening its dramatic truth, orchestral richness, and psychological realism. From early patriotic works to his late Shakespearean masterpieces, he redefined the genre.",
    "key_figures": [
      "Giuseppe Verdi"
    ],
    "entries": [
      {
        "year": 1842,
        "year_label": "1842",
        "title": "Nabucco",
        "composer": "Giuseppe Verdi",
        "kind": "opera",
        "description": "Verdi's first triumph, its chorus 'Va, pensiero' becoming an anthem of Italian national feeling."
      },
      {
        "year": 1851,
        "year_label": "1851",
        "title": "Rigoletto",
        "composer": "Giuseppe Verdi",
        "kind": "opera",
        "description": "Verdi's dark drama of a court jester, marked by psychological depth and the famous quartet 'Bella figlia'."
      },
      {
        "year": 1853,
        "year_label": "1853",
        "title": "La traviata",
        "composer": "Giuseppe Verdi",
        "kind": "opera",
        "description": "Verdi's intimate tragedy of a Parisian courtesan, groundbreaking in its contemporary setting and emotional realism."
      },
      {
        "year": 1871,
        "year_label": "1871",
        "title": "Aida",
        "composer": "Giuseppe Verdi",
        "kind": "opera",
        "description": "Verdi's grand Egyptian epic premiered in Cairo, uniting spectacle with tender personal drama."
      },
      {
        "year": 1887,
        "year_label": "1887",
        "title": "Otello",
        "composer": "Giuseppe Verdi",
        "kind": "opera",
        "description": "Verdi's late Shakespearean tragedy, a continuous musical drama of unprecedented power and structural integration."
      },
      {
        "year": 1893,
        "year_label": "1893",
        "title": "Falstaff",
        "composer": "Giuseppe Verdi",
        "kind": "opera",
        "description": "Verdi's final opera, a sparkling Shakespearean comedy composed at eighty, crowning his career with wit."
      }
    ]
  },
  {
    "id": "21",
    "name": "Wagner & Music Drama",
    "start": 1850,
    "end": 1883,
    "blurb": "Wagner reinvents opera as continuous, leitmotif-woven music drama.",
    "summary": "Richard Wagner transformed opera into the Gesamtkunstwerk, a total artwork uniting music, poetry, and staging through continuous melody and the leitmotif. His theories and works reshaped the harmonic and dramatic possibilities of Western music.",
    "key_figures": [
      "Richard Wagner"
    ],
    "entries": [
      {
        "year": 1850,
        "year_label": "1850",
        "title": "Lohengrin",
        "composer": "Richard Wagner",
        "kind": "opera",
        "description": "Premiered under Liszt at Weimar, Lohengrin marked Wagner's shift toward continuous, myth-driven Romantic opera."
      },
      {
        "year": 1851,
        "year_label": "1851",
        "title": "Oper und Drama",
        "composer": "Richard Wagner",
        "kind": "innovation",
        "description": "Wagner's treatise laid out music drama theory and the leitmotif, subordinating music to unified dramatic expression."
      },
      {
        "year": 1865,
        "year_label": "1865",
        "title": "Tristan und Isolde",
        "composer": "Richard Wagner",
        "kind": "opera",
        "description": "Its unresolved opening chord and chromatic yearning pushed tonality to its limits, foreshadowing modern harmony."
      },
      {
        "year": 1868,
        "year_label": "1868",
        "title": "Die Meistersinger von Nurnberg",
        "composer": "Richard Wagner",
        "kind": "opera",
        "description": "Wagner's grand comedy celebrated German art and counterpoint while dramatizing tradition versus artistic innovation."
      },
      {
        "year": 1876,
        "year_label": "1876",
        "title": "Der Ring des Nibelungen",
        "composer": "Richard Wagner",
        "kind": "opera",
        "description": "The four-opera cycle premiered at the purpose-built Bayreuth Festspielhaus, an epic monument of leitmotif technique."
      },
      {
        "year": 1876,
        "year_label": "1876",
        "title": "Bayreuth Festspielhaus",
        "composer": "Richard Wagner",
        "kind": "institution",
        "description": "Wagner's custom festival theater with hidden orchestra pit was built to stage the Ring under ideal conditions."
      },
      {
        "year": 1882,
        "year_label": "1882",
        "title": "Parsifal",
        "composer": "Richard Wagner",
        "kind": "opera",
        "description": "Wagner's final sacred music drama, a Buhnenweihfestspiel, premiered at Bayreuth, blending religion, redemption, and radiant orchestration."
      }
    ]
  },
  {
    "id": "22",
    "name": "Late Romanticism: Brahms to Mahler",
    "start": 1865,
    "end": 1911,
    "blurb": "Symphonic Romanticism expands from Brahms to Mahler's vast worlds.",
    "summary": "The late Romantic era saw the symphony reach monumental scale and emotional depth through Brahms, Bruckner, Tchaikovsky, Dvorak, and Mahler. National voices and expanded orchestras carried Romanticism toward the edge of modernism.",
    "key_figures": [
      "Johannes Brahms",
      "Anton Bruckner",
      "Pyotr Ilyich Tchaikovsky",
      "Antonin Dvorak",
      "Gustav Mahler"
    ],
    "entries": [
      {
        "year": 1876,
        "year_label": "1876",
        "title": "Symphony No. 1 in C minor",
        "composer": "Johannes Brahms",
        "kind": "work",
        "description": "After decades of labor, Brahms's first symphony affirmed the Classical form against Wagnerian music drama."
      },
      {
        "year": 1877,
        "year_label": "1877",
        "title": "Symphony No. 2 in D major",
        "composer": "Johannes Brahms",
        "kind": "work",
        "description": "A sunlit, pastoral counterpart to his first, composed swiftly and warmly lyrical throughout."
      },
      {
        "year": 1884,
        "year_label": "1884",
        "title": "Symphony No. 7 in E major",
        "composer": "Anton Bruckner",
        "kind": "work",
        "description": "Bruckner's breakthrough symphony brought his cathedral-like structures and Wagnerian sonorities lasting acclaim."
      },
      {
        "year": 1888,
        "year_label": "1888",
        "title": "Symphony No. 5 in E minor",
        "composer": "Pyotr Ilyich Tchaikovsky",
        "kind": "work",
        "description": "A cyclic fate motif unifies this intensely emotional symphony, among Tchaikovsky's most popular orchestral works."
      },
      {
        "year": 1893,
        "year_label": "1893",
        "title": "Symphony No. 9 From the New World",
        "composer": "Antonin Dvorak",
        "kind": "work",
        "description": "Written in America, Dvorak's ninth wove folk-inspired melodies into a beloved late-Romantic symphony."
      },
      {
        "year": 1902,
        "year_label": "1902",
        "title": "Symphony No. 5",
        "composer": "Gustav Mahler",
        "kind": "work",
        "description": "Its famous Adagietto and vast five-movement arc epitomize Mahler's expansion of the symphony's scale and expression."
      },
      {
        "year": 1908,
        "year_label": "1908",
        "title": "Das Lied von der Erde",
        "composer": "Gustav Mahler",
        "kind": "work",
        "description": "A symphonic song cycle on Chinese poetry, meditating on farewell, marks Mahler's late valedictory style."
      }
    ]
  },
  {
    "id": "23",
    "name": "Verismo & Post-Romantic Opera",
    "start": 1890,
    "end": 1924,
    "blurb": "Italian verismo and Strauss push opera toward raw realism.",
    "summary": "Verismo brought gritty realism and passionate melody to Italian opera through Mascagni, Leoncavallo, and above all Puccini. In Germany, Richard Strauss extended post-Romantic opera and the tone poem toward dissonant psychological extremes.",
    "key_figures": [
      "Giacomo Puccini",
      "Pietro Mascagni",
      "Ruggero Leoncavallo",
      "Richard Strauss"
    ],
    "entries": [
      {
        "year": 1890,
        "year_label": "1890",
        "title": "Cavalleria rusticana",
        "composer": "Pietro Mascagni",
        "kind": "opera",
        "description": "This one-act tragedy of Sicilian passion launched the verismo movement with vivid realism and surging lyricism."
      },
      {
        "year": 1892,
        "year_label": "1892",
        "title": "Pagliacci",
        "composer": "Ruggero Leoncavallo",
        "kind": "opera",
        "description": "A clown's jealous murder blurs stage and life in this quintessential verismo drama of raw emotion."
      },
      {
        "year": 1896,
        "year_label": "1896",
        "title": "La Boheme",
        "composer": "Giacomo Puccini",
        "kind": "opera",
        "description": "Puccini's tender tragedy of bohemian Paris lovers became one of the most beloved operas ever written."
      },
      {
        "year": 1900,
        "year_label": "1900",
        "title": "Tosca",
        "composer": "Giacomo Puccini",
        "kind": "opera",
        "description": "A taut political thriller of love, torture, and death, Tosca fused verismo intensity with soaring melody."
      },
      {
        "year": 1904,
        "year_label": "1904",
        "title": "Madama Butterfly",
        "composer": "Giacomo Puccini",
        "kind": "opera",
        "description": "Puccini's tragedy of a betrayed Japanese bride recovered from a disastrous premiere to become a global favorite."
      },
      {
        "year": 1905,
        "year_label": "1905",
        "title": "Salome",
        "composer": "Richard Strauss",
        "kind": "opera",
        "description": "Strauss's lurid, dissonant one-act shocked audiences and pushed opera toward Expressionist psychological extremes."
      },
      {
        "year": 1909,
        "year_label": "1909",
        "title": "Elektra",
        "composer": "Richard Strauss",
        "kind": "opera",
        "description": "Strauss and librettist Hofmannsthal drove harmony to near-atonal violence in this ferocious Greek tragedy."
      }
    ]
  },
  {
    "id": "24",
    "name": "Impressionism & Early Modernism",
    "start": 1894,
    "end": 1920,
    "blurb": "Debussy and Ravel dissolve tonality into color and atmosphere.",
    "summary": "French Impressionism, led by Debussy and Ravel, replaced Germanic development with shimmering color, whole-tone scales, and atmosphere. Alongside Scriabin's mystic harmonies, it opened the door to twentieth-century modernism.",
    "key_figures": [
      "Claude Debussy",
      "Maurice Ravel",
      "Alexander Scriabin"
    ],
    "entries": [
      {
        "year": 1894,
        "year_label": "1894",
        "title": "Prelude a l'apres-midi d'un faune",
        "composer": "Claude Debussy",
        "kind": "work",
        "description": "Its sensuous, free-floating orchestral color is often cited as the dawn of musical modernism."
      },
      {
        "year": 1902,
        "year_label": "1902",
        "title": "Pelleas et Melisande",
        "composer": "Claude Debussy",
        "kind": "opera",
        "description": "Debussy's only completed opera set subtle, symbolist drama to understated, atmospheric declamation rather than aria."
      },
      {
        "year": 1905,
        "year_label": "1905",
        "title": "La Mer",
        "composer": "Claude Debussy",
        "kind": "work",
        "description": "Three symphonic sketches of the sea display Debussy's mastery of orchestral color and shifting texture."
      },
      {
        "year": 1908,
        "year_label": "1908",
        "title": "The Poem of Ecstasy",
        "composer": "Alexander Scriabin",
        "kind": "work",
        "description": "Scriabin's rapturous tone poem pushed lush chromatic harmony toward his personal mystic and synesthetic idiom."
      },
      {
        "year": 1912,
        "year_label": "1912",
        "title": "Daphnis et Chloe",
        "composer": "Maurice Ravel",
        "kind": "work",
        "description": "Ravel's opulent ballet score, his largest work, epitomizes refined orchestration and luminous Impressionist color."
      },
      {
        "year": 1918,
        "year_label": "1918",
        "title": "Le Tombeau de Couperin",
        "composer": "Maurice Ravel",
        "kind": "work",
        "description": "A neoclassical suite honoring Baroque France and fallen wartime friends signaled a turn beyond Impressionism."
      }
    ]
  },
  {
    "id": "25",
    "name": "Neo-Classicism & Stravinsky",
    "start": 1920,
    "end": 1950,
    "blurb": "Return to clarity, form, and past styles after Romantic excess.",
    "summary": "Composers reacted against late-Romantic expansiveness by reviving Classical and Baroque forms, balance, and restraint. Stravinsky led the movement while Prokofiev, Bartok, and Shostakovich forged distinct modern-tonal voices.",
    "key_figures": [
      "Igor Stravinsky",
      "Sergei Prokofiev",
      "Bela Bartok",
      "Dmitri Shostakovich",
      "Paul Hindemith"
    ],
    "entries": [
      {
        "year": 1913,
        "year_label": "1913",
        "title": "The Rite of Spring",
        "composer": "Igor Stravinsky",
        "kind": "work",
        "description": "Precursor ballet whose driving rhythms and dissonance sparked a riot at its Paris premiere and reshaped modern music."
      },
      {
        "year": 1920,
        "year_label": "1920",
        "title": "Pulcinella",
        "composer": "Igor Stravinsky",
        "kind": "work",
        "description": "Ballet reworking music attributed to Pergolesi, marking Stravinsky's turn toward Neo-Classicism and eighteenth-century models."
      },
      {
        "year": 1930,
        "year_label": "1930",
        "title": "Symphony of Psalms",
        "composer": "Igor Stravinsky",
        "kind": "work",
        "description": "Choral symphony setting Latin psalms with austere grandeur, a landmark of his religious Neo-Classical style."
      },
      {
        "year": 1936,
        "year_label": "1936",
        "title": "Peter and the Wolf",
        "composer": "Sergei Prokofiev",
        "kind": "work",
        "description": "Orchestral fairy tale introducing children to instruments through memorable character themes, one of his most beloved works."
      },
      {
        "year": 1937,
        "year_label": "1937",
        "title": "Symphony No. 5",
        "composer": "Dmitri Shostakovich",
        "kind": "work",
        "description": "Written under Soviet pressure, its powerful drama became one of the twentieth century's most performed symphonies."
      },
      {
        "year": 1943,
        "year_label": "1943",
        "title": "Concerto for Orchestra",
        "composer": "Bela Bartok",
        "kind": "work",
        "description": "Late masterwork blending Hungarian folk idioms with virtuosic orchestral color, a summit of Bartok's mature style."
      }
    ]
  },
  {
    "id": "26",
    "name": "The Second Viennese School",
    "start": 1908,
    "end": 1950,
    "blurb": "Schoenberg and pupils break tonality and invent twelve-tone music.",
    "summary": "Arnold Schoenberg and his students Alban Berg and Anton Webern abandoned traditional tonality, then developed the twelve-tone method to organize atonal music. Their work redefined harmony and profoundly shaped later modernism.",
    "key_figures": [
      "Arnold Schoenberg",
      "Alban Berg",
      "Anton Webern"
    ],
    "entries": [
      {
        "year": 1908,
        "year_label": "1908",
        "title": "Emancipation of Dissonance",
        "composer": "Arnold Schoenberg",
        "kind": "innovation",
        "description": "Schoenberg's move into free atonality, abandoning traditional harmonic centers in works like the Second String Quartet."
      },
      {
        "year": 1912,
        "year_label": "1912",
        "title": "Pierrot Lunaire",
        "composer": "Arnold Schoenberg",
        "kind": "work",
        "description": "Expressionist song cycle for reciter and ensemble using Sprechstimme, a defining work of early atonality."
      },
      {
        "year": 1923,
        "year_label": "1923",
        "title": "The Twelve-Tone Method",
        "composer": "Arnold Schoenberg",
        "kind": "innovation",
        "description": "Systematic technique ordering all twelve chromatic pitches into a row, giving atonal music new structural coherence."
      },
      {
        "year": 1925,
        "year_label": "1925",
        "title": "Wozzeck",
        "composer": "Alban Berg",
        "kind": "opera",
        "description": "Harrowing atonal opera about a downtrodden soldier, a twentieth-century operatic landmark of psychological intensity."
      },
      {
        "year": 1932,
        "year_label": "1932",
        "title": "Moses und Aron",
        "composer": "Arnold Schoenberg",
        "kind": "opera",
        "description": "Unfinished twelve-tone opera on faith and representation, among the most ambitious serial stage works."
      },
      {
        "year": 1936,
        "year_label": "1936",
        "title": "Violin Concerto",
        "composer": "Alban Berg",
        "kind": "work",
        "description": "Lyrical twelve-tone concerto dedicated 'to the memory of an angel,' reconciling serialism with tonal expressiveness."
      },
      {
        "year": 1937,
        "year_label": "1937",
        "title": "Lulu",
        "composer": "Alban Berg",
        "kind": "opera",
        "description": "Unfinished twelve-tone opera of desire and downfall, left incomplete at Berg's death and premiered in part in 1937."
      }
    ]
  },
  {
    "id": "27",
    "name": "Postwar Avant-Garde & Serialism",
    "start": 1945,
    "end": 1975,
    "blurb": "Total serialism, chance, and electronics push music's boundaries.",
    "summary": "After World War II, composers extended serial thinking to all musical parameters while others embraced chance, electronics, and dense textures. Darmstadt became the crucible for a radical rethinking of what music could be.",
    "key_figures": [
      "Pierre Boulez",
      "Karlheinz Stockhausen",
      "John Cage",
      "Olivier Messiaen",
      "Gyorgy Ligeti",
      "Krzysztof Penderecki"
    ],
    "entries": [
      {
        "year": 1948,
        "year_label": "1948",
        "title": "Turangalila-Symphonie",
        "composer": "Olivier Messiaen",
        "kind": "work",
        "description": "Vast ten-movement symphony celebrating love, featuring the ondes Martenot and Messiaen's vivid rhythmic and harmonic language."
      },
      {
        "year": 1952,
        "year_label": "1952",
        "title": "4'33\"",
        "composer": "John Cage",
        "kind": "work",
        "description": "Silent piece framing ambient sound as music, a radical statement on indeterminacy and the nature of listening."
      },
      {
        "year": 1955,
        "year_label": "1955",
        "title": "Le Marteau sans maitre",
        "composer": "Pierre Boulez",
        "kind": "work",
        "description": "Intricate serial setting of Char's poetry for voice and ensemble, an emblem of postwar avant-garde rigor."
      },
      {
        "year": 1956,
        "year_label": "1956",
        "title": "Gesang der Junglinge",
        "composer": "Karlheinz Stockhausen",
        "kind": "work",
        "description": "Pioneering electronic work fusing recorded boy's voice with synthesized sound, a milestone of the electronic studio."
      },
      {
        "year": 1960,
        "year_label": "1960",
        "title": "Threnody to the Victims of Hiroshima",
        "composer": "Krzysztof Penderecki",
        "kind": "work",
        "description": "String work of clustered, sliding textures giving voice to catastrophe, a landmark of sonorism."
      },
      {
        "year": 1961,
        "year_label": "1961",
        "title": "Atmospheres",
        "composer": "Gyorgy Ligeti",
        "kind": "work",
        "description": "Slowly shifting orchestral micropolyphony creating dense clouds of sound, later famed for use in a Kubrick film."
      }
    ]
  },
  {
    "id": "28",
    "name": "Minimalism & Postmodernism",
    "start": 1965,
    "end": 2000,
    "blurb": "Repetition and pulse return; American minimalism reshapes music.",
    "summary": "American composers built music from steady pulses, gradual processes, and repeating patterns, rejecting serialist complexity. Minimalism spread into opera and beyond while a plural postmodern landscape embraced tonality anew.",
    "key_figures": [
      "Steve Reich",
      "Philip Glass",
      "John Adams",
      "Arvo Part",
      "Terry Riley"
    ],
    "entries": [
      {
        "year": 1964,
        "year_label": "1964",
        "title": "In C",
        "composer": "Terry Riley",
        "kind": "work",
        "description": "Open-ended set of repeating cells for any ensemble, a founding work of American minimalism."
      },
      {
        "year": 1976,
        "year_label": "1976",
        "title": "Music for 18 Musicians",
        "composer": "Steve Reich",
        "kind": "work",
        "description": "Pulsing, interlocking patterns over shifting harmonies, a landmark that broadened minimalism's expressive range."
      },
      {
        "year": 1976,
        "year_label": "1976",
        "title": "Einstein on the Beach",
        "composer": "Philip Glass",
        "kind": "opera",
        "description": "Groundbreaking non-narrative opera with Robert Wilson, redefining the form through repetition and abstract staging."
      },
      {
        "year": 1977,
        "year_label": "1977",
        "title": "Tabula Rasa",
        "composer": "Arvo Part",
        "kind": "work",
        "description": "Serene work introducing Part's tintinnabuli style, central to a spare, spiritual strand of contemporary music."
      },
      {
        "year": 1987,
        "year_label": "1987",
        "title": "Nixon in China",
        "composer": "John Adams",
        "kind": "opera",
        "description": "Opera dramatizing the 1972 presidential visit, bringing minimalism to contemporary historical subjects."
      },
      {
        "year": 1988,
        "year_label": "1988",
        "title": "Different Trains",
        "composer": "Steve Reich",
        "kind": "work",
        "description": "String quartet with recorded speech evoking wartime train journeys, pioneering the use of documentary voices in music."
      }
    ]
  },
  {
    "id": "29",
    "name": "Contemporary Opera & the 21st Century",
    "start": 2000,
    "end": 2025,
    "blurb": "New voices expand opera and orchestral music worldwide.",
    "summary": "The new century saw diverse styles coexist, with opera experiencing a creative resurgence through composers exploring new subjects and sonorities. Pulitzer-winning works and international premieres marked a vibrant contemporary scene.",
    "key_figures": [
      "Kaija Saariaho",
      "Thomas Ades",
      "John Adams",
      "George Benjamin",
      "Jennifer Higdon"
    ],
    "entries": [
      {
        "year": 2000,
        "year_label": "2000",
        "title": "L'Amour de loin",
        "composer": "Kaija Saariaho",
        "kind": "opera",
        "description": "Luminous opera of distant love, acclaimed at its Salzburg premiere and among the era's most celebrated new operas."
      },
      {
        "year": 2004,
        "year_label": "2004",
        "title": "The Tempest",
        "composer": "Thomas Ades",
        "kind": "opera",
        "description": "Inventive setting of Shakespeare's play for the Royal Opera, confirming Ades as a leading operatic voice."
      },
      {
        "year": 2005,
        "year_label": "2005",
        "title": "Doctor Atomic",
        "composer": "John Adams",
        "kind": "opera",
        "description": "Opera on Robert Oppenheimer and the atomic bomb's creation, probing science, conscience, and dread."
      },
      {
        "year": 2012,
        "year_label": "2012",
        "title": "Written on Skin",
        "composer": "George Benjamin",
        "kind": "opera",
        "description": "Widely praised opera of medieval passion and violence, hailed as a modern masterpiece after its Aix-en-Provence premiere."
      },
      {
        "year": 2015,
        "year_label": "2015",
        "title": "Anthracite Fields",
        "composer": "Julia Wolfe",
        "kind": "work",
        "description": "Pulitzer-winning oratorio memorializing Pennsylvania coal miners through text, song, and driving instrumental writing."
      },
      {
        "year": 2017,
        "year_label": "2017",
        "title": "Angel's Bone",
        "composer": "Du Yun",
        "kind": "opera",
        "description": "Pulitzer-winning opera confronting human trafficking through a fusion of operatic and popular idioms."
      }
    ]
  }
];
