/* @provenance: BORG-PROVENANCE-STANDARD-2026-03
 * @orchestrator: Magnus Smárason | smarason.is
 * @created: 2026-07-29
 */

export interface UpdateEntry {
  date: string;
  version?: string;
  title: string;
  /** Markdown-lite: **bold** and [text](/href) links only. */
  body: string;
  tags: string[];
}

// Newest first. Append new entries at the top.
export const UPDATES: UpdateEntry[] = [
  {
    date: "2026-07-29",
    title: "Per-page metadata for every year and era",
    body:
      "All 5,226 year pages and every scholarly era now emit their own title, description and social card, built from that year's own headline events; previously they shared one generic site-wide card.",
    tags: ["seo", "metadata"],
  },
  {
    date: "2026-07-29",
    title: "Era expansion: 21 new scholarly eras defined",
    body:
      "The era model is being extended beyond the linear chronological sweep with thematic lenses (Scientific Revolution, Age of Revolutions, Decolonisation), crisis eras (the Transatlantic Slave Trade, the Black Death, the World Wars) and regional spheres (West African Golden Age, Tang and Song China, Classic Maya). Note that these overlap each other by design and that research is in progress, not complete.",
    tags: ["eras", "research"],
  },
  {
    date: "2026-07-29",
    title: "Research provenance: angle generation separated from evidence",
    body:
      "Research angles and source-bias audits are now generated by one model and the supporting evidence retrieved and verified independently against the scholarly literature, so no single model both proposes a claim and supplies its own support.",
    tags: ["methodology", "evidence"],
  },
  {
    date: "2026-07-16",
    version: "music in the timeline",
    title: "Classical music & opera merged into the major timeline",
    body:
      "The 29-era classical music and opera dataset is no longer a separate section. Its 233 events now sit inside the main year-by-year timeline, tagged **Music & Opera**, filterable like any other category. The standalone header menu was removed in favour of this tag. The full per-era scholarly folio, with all sources, lives at the [music & opera folio](/music).",
    tags: ["timeline", "music & opera", "tagging"],
  },
  {
    date: "2026-07-16",
    version: "integrity",
    title: "Every scholarly source verified against Crossref and DataCite",
    body:
      "The 161 Layer 2 citations were independently checked against the Crossref and DataCite registries. Every DOI resolves to a real paper; the title and author names shown now come straight from those registries (an earlier pass had placed journal names in the author field). Zero fabricated citations, zero retractions.",
    tags: ["evidence", "verification", "crossref", "datacite"],
  },
  {
    date: "2026-07-15",
    version: "Layer 2",
    title: "Scholarly evidence layer added via a Scite research swarm",
    body:
      "A 29-agent Scite MCP research swarm gathered **161 peer-reviewed sources** across all 29 music eras, retraction-enforced. Each era gained a scholarly-evidence panel with a synthesis, sources carrying a stance (supporting / contested / background), and the real debates historians are still having.",
    tags: ["evidence", "scite", "scholarship"],
  },
  {
    date: "2026-07-15",
    version: "Layer 1",
    title: "Classical music & opera timeline",
    body:
      "A 29-era chronicle of Western classical music and opera, from Gregorian plainchant to twenty-first-century opera, generated by a parallel agent swarm. Every entry carries a place and an honest historical-confidence level (confirmed to legendary).",
    tags: ["timeline", "music & opera", "Layer 1"],
  },
  {
    date: "2026-04-18",
    version: "localisation",
    title: "Icelandic translation pipeline",
    body:
      "A CI-integrated pipeline localises the year-level corpus into Icelandic with strict schema and structural guards, so a new English year automatically produces a schema-valid Icelandic counterpart.",
    tags: ["i18n", "icelandic", "pipeline"],
  },
  {
    date: "2026-04-18",
    version: "frontend rebuild",
    title: "The Notebook, Stratum and Atlas views",
    body:
      "A wholesale editorial rebuild: the parchment Notebook timeline, the Stratum data view, and the map-anchored Atlas globe, with a two-layer navigation and the methodology folio.",
    tags: ["frontend", "design", "atlas"],
  },
  {
    date: "2026-04-13",
    version: "Phase 1",
    title: "The 5,226-year corpus",
    body:
      "The founding layer: every year from roughly 3200 BCE to 2025 CE researched by an async daemon under the ICCRA schema, 17,991 events with sources, certainty levels, and declared gaps. This is the timeline the music & opera work now sits inside.",
    tags: ["corpus", "ICCRA", "foundation"],
  },
];
