/* @provenance: BORG-PROVENANCE-STANDARD-2026-03
 * @orchestrator: Magnus Smárason | smarason.is
 * @created: 2026-07-16
 */
import type { Metadata } from "next";
import Link from "next/link";
import "./updates.css";

export const metadata: Metadata = {
  title: "Updates",
  description:
    "Changelog for the Chronograph timeline: what was added, verified, and changed, with dates and provenance.",
};

interface Update {
  date: string;
  version?: string;
  title: string;
  body: React.ReactNode;
  tags: string[];
}

// Newest first. Append new entries at the top.
const UPDATES: Update[] = [
  {
    date: "2026-07-16",
    version: "music in the timeline",
    title: "Classical music & opera merged into the major timeline",
    body: (
      <>
        The 29-era classical music and opera dataset is no longer a separate
        section. Its 233 events now sit inside the main year-by-year timeline,
        tagged <strong>Music &amp; Opera</strong>, filterable like any other
        category. The standalone header menu was removed in favour of this tag.
        The full per-era scholarly folio, with all sources, lives at the{" "}
        <Link href="/music">music &amp; opera folio</Link>.
      </>
    ),
    tags: ["timeline", "music & opera", "tagging"],
  },
  {
    date: "2026-07-16",
    version: "integrity",
    title: "Every scholarly source verified against Crossref and DataCite",
    body: (
      <>
        The 161 Layer 2 citations were independently checked against the Crossref
        and DataCite registries. Every DOI resolves to a real paper; the title and
        author names shown now come straight from those registries (an earlier
        pass had placed journal names in the author field). Zero fabricated
        citations, zero retractions.
      </>
    ),
    tags: ["evidence", "verification", "crossref", "datacite"],
  },
  {
    date: "2026-07-15",
    version: "Layer 2",
    title: "Scholarly evidence layer added via a Scite research swarm",
    body: (
      <>
        A 29-agent Scite MCP research swarm gathered <strong>161 peer-reviewed
        sources</strong> across all 29 music eras, retraction-enforced. Each era
        gained a scholarly-evidence panel with a synthesis, sources carrying a
        stance (supporting / contested / background), and the real debates
        historians are still having.
      </>
    ),
    tags: ["evidence", "scite", "scholarship"],
  },
  {
    date: "2026-07-15",
    version: "Layer 1",
    title: "Classical music & opera timeline",
    body: (
      <>
        A 29-era chronicle of Western classical music and opera, from Gregorian
        plainchant to twenty-first-century opera, generated by a parallel agent
        swarm. Every entry carries a place and an honest historical-confidence
        level (confirmed to legendary).
      </>
    ),
    tags: ["timeline", "music & opera", "Layer 1"],
  },
  {
    date: "2026-04-18",
    version: "localisation",
    title: "Icelandic translation pipeline",
    body: (
      <>
        A CI-integrated pipeline localises the year-level corpus into Icelandic
        with strict schema and structural guards, so a new English year
        automatically produces a schema-valid Icelandic counterpart.
      </>
    ),
    tags: ["i18n", "icelandic", "pipeline"],
  },
  {
    date: "2026-04-18",
    version: "frontend rebuild",
    title: "The Notebook, Stratum and Atlas views",
    body: (
      <>
        A wholesale editorial rebuild: the parchment Notebook timeline, the
        Stratum data view, and the map-anchored Atlas globe, with a two-layer
        navigation and the methodology folio.
      </>
    ),
    tags: ["frontend", "design", "atlas"],
  },
  {
    date: "2026-04-13",
    version: "Phase 1",
    title: "The 5,226-year corpus",
    body: (
      <>
        The founding layer: every year from roughly 3200 BCE to 2025 CE
        researched by an async daemon under the ICCRA schema, 17,991 events with
        sources, certainty levels, and declared gaps. This is the timeline the
        music &amp; opera work now sits inside.
      </>
    ),
    tags: ["corpus", "ICCRA", "foundation"],
  },
];

export default function UpdatesPage() {
  return (
    <div className="up">
      <div className="up-wrap">
        <div className="up-kicker">Changelog</div>
        <h1>Updates to the timeline</h1>
        <p className="up-lede">
          What was added, verified, and changed, with dates. This project is a
          glass box: the method and its revisions are part of the record.
        </p>

        <ol className="up-list">
          {UPDATES.map((u) => (
            <li className="up-item" key={`${u.date}-${u.title}`}>
              <div className="up-date">
                <time dateTime={u.date}>{u.date}</time>
                {u.version ? <span className="up-ver">{u.version}</span> : null}
              </div>
              <div>
                <h2 className="up-title">{u.title}</h2>
                <div className="up-body">{u.body}</div>
                <div className="up-tags">
                  {u.tags.map((t) => (
                    <span className="up-tag" key={t}>
                      {t}
                    </span>
                  ))}
                </div>
              </div>
            </li>
          ))}
        </ol>

        <p className="up-foot">
          The full commit history lives on{" "}
          <a
            href="https://github.com/Magnussmari/Human_history_Acording_to_AI"
            target="_blank"
            rel="noopener noreferrer"
          >
            GitHub
          </a>
          . For how the timeline is built and its honesty protocol, see the{" "}
          <Link href="/methodology">methodology</Link>.
        </p>
      </div>
    </div>
  );
}
