/* @provenance: BORG-PROVENANCE-STANDARD-2026-03
 * @orchestrator: Magnus Smárason | smarason.is
 * @created: 2026-04-18
 */
"use client";

import Link from "next/link";
import { useState } from "react";
import { motion } from "motion/react";
import type { YearData, HistoryEvent } from "@/types/history";
import { getEraForYear, safeCategoryConfig } from "@/lib/constants";
import { ScholarlyEraCard } from "@/components/ScholarlyEraCard";
import "./notebook-folio.css";

interface NotebookYearFolioProps {
  year: YearData;
}

const CERTAINTY_RANK: Record<string, number> = {
  legendary: 1,
  traditional: 2,
  approximate: 2,
  probable: 3,
  confirmed: 4,
};

const RELATION_LABELS: Record<string, string> = {
  caused_by: "caused by",
  led_to: "led to",
  contemporary_with: "contemporary with",
  contradicts: "contradicts",
  part_of: "part of",
};

function yearOrdinal(y: number, total: number): string {
  const ordinal = y + 3201; // corpus oldest year is ~-3200
  return `${String(ordinal).padStart(4, "0")} / ${total.toLocaleString()}`;
}

export function NotebookYearFolio({ year }: NotebookYearFolioProps) {
  const era = getEraForYear(year.year);
  const totalSources = year.events.reduce((a, e) => a + e.sources.length, 0);

  return (
    <article className="notebook-folio">
      <Link href="/" className="notebook-folio-back">
        ← Back to timeline
      </Link>

      <motion.header
        className="notebook-folio-hero"
        initial={{ opacity: 0, y: 8 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.45, ease: [0.16, 1, 0.3, 1] }}
      >
        <div className="notebook-folio-hero-grid">
          <div className="notebook-folio-eyebrow">
            <span className="notebook-stamp">Folio</span>
            <span className="notebook-folio-ordinal">
              Vol. I · Entry {yearOrdinal(year.year, 5226)}
            </span>
          </div>

          <h1 className="notebook-folio-title">
            <span className="notebook-folio-year-num">
              {Math.abs(year.year).toLocaleString()}
            </span>
            <span className="notebook-folio-year-era">
              {year.year < 0 ? "BCE" : "CE"}
            </span>
          </h1>

          <div className="notebook-folio-hero-meta">
            <span className="notebook-folio-hero-meta-era">{era.label}</span>
            <span className="notebook-folio-dot">·</span>
            <span>{year.events.length} events</span>
            <span className="notebook-folio-dot">·</span>
            <span className="capitalize">{year.documentation_level} documentation</span>
            <span className="notebook-folio-dot">·</span>
            <span>{totalSources} cited sources</span>
          </div>
        </div>

        <aside className="notebook-folio-sidenote">
          <div className="notebook-folio-sidenote-label">Editor&apos;s note</div>
          <p>
            Year-by-year structured records generated by Claude Sonnet under
            the ICCRA schema. Every event carries a certainty level and the
            contemporary-vs-later mix of its sources. Read with the same
            scepticism you would bring to any secondary source.
          </p>
        </aside>
      </motion.header>

      <section className="notebook-folio-era">
        <div className="notebook-folio-era-rule" />
        <div className="notebook-folio-era-body">
          <div className="notebook-folio-era-label">Era context</div>
          <p className="notebook-folio-era-text">{year.era_context}</p>

          {year.geographic_coverage_gaps.length > 0 && (
            <div className="notebook-folio-gaps">
              <span className="notebook-folio-gap-label">Coverage gaps ·</span>
              {year.geographic_coverage_gaps.map((g, i) => (
                <span key={i} className="notebook-folio-gap-chip">{g}</span>
              ))}
            </div>
          )}
        </div>
      </section>

      <section className="notebook-folio-scholar">
        <ScholarlyEraCard year={year.year} />
      </section>

      <section className="notebook-folio-section">
        <header className="notebook-folio-section-head">
          <span className="notebook-folio-section-num">§ 01</span>
          <h2>Events</h2>
          <span className="notebook-folio-section-trail">
            — chronological, as attested
          </span>
        </header>

        <ol className="notebook-folio-entries">
          {year.events.map((ev, i) => (
            <NotebookFolioEntry key={ev.id} ev={ev} idx={i} />
          ))}
        </ol>
      </section>

      {year.disconfirming_evidence && (
        <section className="notebook-folio-section notebook-folio-dissent-block">
          <header className="notebook-folio-section-head">
            <span className="notebook-folio-section-num">§ 02</span>
            <h2>Disconfirming evidence</h2>
            <span className="notebook-folio-section-trail">
              — where this account breaks down
            </span>
          </header>
          <div className="notebook-folio-dissent-body">
            <div className="notebook-folio-dissent-mark">¶</div>
            <p>{year.disconfirming_evidence}</p>
          </div>
        </section>
      )}

      {year.historiographic_note && (
        <section className="notebook-folio-section notebook-folio-dissent-block">
          <header className="notebook-folio-section-head">
            <span className="notebook-folio-section-num">§ 03</span>
            <h2>Historiographic note</h2>
            <span className="notebook-folio-section-trail">
              — on the shape of the record itself
            </span>
          </header>
          <div className="notebook-folio-dissent-body">
            <div className="notebook-folio-dissent-mark">¶</div>
            <p>{year.historiographic_note}</p>
          </div>
        </section>
      )}

      {year.graph_edges.length > 0 && (
        <section className="notebook-folio-section notebook-folio-edges-block">
          <header className="notebook-folio-section-head">
            <span className="notebook-folio-section-num">§ 04</span>
            <h2>Cross-year connections</h2>
            <span className="notebook-folio-section-trail">
              — graph edges in the corpus
            </span>
          </header>
          <ul className="notebook-folio-edges">
            {year.graph_edges.map((edge, i) => {
              const fromYear = Number.parseInt(edge.from.split("_")[0]?.split("-")[0] ?? "", 10);
              const toYear = Number.parseInt(edge.to.split("_")[0]?.split("-")[0] ?? "", 10);
              const relation = RELATION_LABELS[edge.relation] ?? edge.relation.replace(/_/g, " ");
              return (
                <li key={i} className="notebook-folio-edge">
                  {Number.isFinite(fromYear) && !Number.isNaN(fromYear) ? (
                    <Link href={`/year/${fromYear}`} className="notebook-folio-edge-id">
                      {edge.from}
                    </Link>
                  ) : (
                    <span className="notebook-folio-edge-id">{edge.from}</span>
                  )}
                  <span className="notebook-folio-edge-rel">{relation}</span>
                  {Number.isFinite(toYear) && !Number.isNaN(toYear) ? (
                    <Link href={`/year/${toYear}`} className="notebook-folio-edge-id">
                      {edge.to}
                    </Link>
                  ) : (
                    <span className="notebook-folio-edge-id">{edge.to}</span>
                  )}
                  {edge.note && (
                    <span className="notebook-folio-edge-note">{edge.note}</span>
                  )}
                </li>
              );
            })}
          </ul>
        </section>
      )}

      <footer className="notebook-folio-footer">
        <div className="notebook-folio-footer-rule" />
        <div className="notebook-folio-footer-row">
          <span>End of entry {yearOrdinal(year.year, 5226)}</span>
          <span className="notebook-folio-footer-year">
            {year.year < 0
              ? `${Math.abs(year.year)} BCE`
              : `${year.year} CE`}
          </span>
          <span>Chronograph · Notebook folio</span>
        </div>

        {year._meta && (
          <div className="notebook-folio-meta">
            <span className="notebook-folio-meta-label">Research metadata</span>
            <span className="notebook-folio-meta-body">
              Model: {year._meta.model}
              {year._meta.method && ` · method: ${year._meta.method}`}
              {year._meta.cost_usd != null && ` · cost: $${year._meta.cost_usd.toFixed(4)}`}
              {year._meta.cached && " · cached"}
              {` · processed ${year._meta.processed_at}`}
            </span>
          </div>
        )}
      </footer>
    </article>
  );
}

interface NotebookFolioEntryProps {
  ev: HistoryEvent;
  idx: number;
}

function NotebookFolioEntry({ ev, idx }: NotebookFolioEntryProps) {
  const [open, setOpen] = useState(false);
  const contemp = ev.sources.filter((s) => s.contemporary).length;
  const later = ev.sources.length - contemp;
  const rank = CERTAINTY_RANK[ev.certainty] ?? 0;
  const catLabel = safeCategoryConfig(ev.category).label;

  return (
    <li className="notebook-folio-entry">
      <div className="notebook-folio-entry-rail">
        <div className="notebook-folio-entry-index">
          {String(idx + 1).padStart(2, "0")}
        </div>
        <div
          className="notebook-folio-entry-dot"
          style={{ background: `var(--cat-${ev.category}, var(--stamp))` }}
        />
      </div>

      <div className="notebook-folio-entry-body">
        <button
          type="button"
          className="notebook-folio-entry-open"
          onClick={() => setOpen((o) => !o)}
          aria-expanded={open}
        >
          <div className="notebook-folio-entry-head">
            <span
              className="notebook-folio-entry-cat"
              style={{ color: `var(--cat-${ev.category}, var(--stamp))` }}
            >
              {catLabel}
            </span>
            <span className="notebook-folio-entry-sep">·</span>
            <span className="notebook-folio-entry-region">{ev.region}</span>
          </div>
          <h3 className="notebook-folio-entry-title">{ev.title}</h3>
          <p
            className="notebook-folio-entry-desc"
            style={{
              WebkitLineClamp: open ? "unset" : 3,
              display: open ? "block" : "-webkit-box",
            }}
          >
            {ev.description}
          </p>

          <div className="notebook-folio-entry-foot">
            <CertaintyStamp certainty={ev.certainty} rank={rank} />
            <div className="notebook-folio-entry-bars">
              <span className="notebook-folio-entry-bars-label">
                Contemp / Later
              </span>
              <span className="notebook-folio-entry-bars-meter">
                <span
                  className="notebook-folio-entry-bar c"
                  style={{ flex: contemp || 0.01 }}
                  title={`${contemp} contemporary`}
                />
                <span
                  className="notebook-folio-entry-bar l"
                  style={{ flex: later || 0.01 }}
                  title={`${later} later`}
                />
              </span>
              <span className="notebook-folio-entry-bars-num">
                {ev.sources.length}
              </span>
            </div>
            <span className="notebook-folio-entry-more">
              {open ? "Collapse ↑" : "Unfold ↓"}
            </span>
          </div>
        </button>

        {open && (
          <div className="notebook-folio-entry-expand">
            {ev.key_figures.length > 0 && (
              <div className="notebook-folio-kf">
                <div className="notebook-folio-kf-label">Figures cited</div>
                <div className="notebook-folio-kf-list">
                  {ev.key_figures.map((f, i) => (
                    <span key={i} className="notebook-folio-kf-chip">{f}</span>
                  ))}
                </div>
              </div>
            )}
            <div className="notebook-folio-sources">
              <div className="notebook-folio-kf-label">Sources</div>
              <ol className="notebook-folio-source-list">
                {ev.sources.map((s, i) => (
                  <li key={i} className="notebook-folio-source">
                    <sup className="notebook-folio-source-num">{i + 1}</sup>
                    <span className="notebook-folio-source-name">{s.name}</span>
                    <span
                      className={
                        "notebook-folio-source-tag " +
                        (s.contemporary ? "contemp" : "later")
                      }
                    >
                      {s.type.replace(/_/g, " ")}
                      {s.contemporary && " · contemporary"}
                    </span>
                  </li>
                ))}
              </ol>
            </div>
            {ev.certainty_note && (
              <p className="notebook-folio-entry-cert-note">
                <span className="notebook-folio-kf-label">Certainty note</span>
                {ev.certainty_note}
              </p>
            )}
          </div>
        )}
      </div>
    </li>
  );
}

function CertaintyStamp({ certainty, rank }: { certainty: string; rank: number }) {
  const label = certainty.charAt(0).toUpperCase() + certainty.slice(1);
  return (
    <span
      className={`notebook-folio-cert notebook-folio-cert-${certainty}`}
      title={`Certainty: ${label}`}
    >
      <span className="notebook-folio-cert-mark">
        {Array.from({ length: 4 }).map((_, i) => (
          <span key={i} className={i < rank ? "on" : ""} />
        ))}
      </span>
      {label}
    </span>
  );
}
